[node]
detect-drivers = false # don't try to find drivers on this computer in the usual places
max-sessions = 1

[relay]
# Default Appium/Cloud server endpoint
url = "http://host.docker.internal:4723/wd/hub" # the server that will be making requests to the grid
status-endpoint = "/status"
# Stereotypes supported by the service. The initial number is "max-sessions", and will allocate 
# that many test slots to that particular configuration
configs = [
  "1", "{\"browserName\": \"chrome\", \"platformName\": \"android\", \"appium:platformVersion\": \"12.0\"}",
  "1", "{\"browserName\": \"safari\", \"platformName\": \"ios\", \"appium:platformVersion\": \"12.0\"}"
]

